### PR TITLE
Draft: Accuracy improvements for rotations

### PR DESCRIPTION
**Pull request by mreineck**
This outlines a method for improving the accuracy of the spherical harmonic rotations.
Please don't take the names of the newly introduced functions too seriously; I'm just trying to illustrate the sort of special-casing/simplifications I made.

### CODE REVIEW

**Comment by mreineck** [comment]
The current state should already improve accuracy noticeably.

The next step requires modifications to `recurrence.h`, which will probably take me some time ...

**Comment by mreineck** [comment]
OK, second stage is now also in.

**Comment by MikaelSlevinsky** [comment]
Thanks! I think the original performance can be maintained by recognizing a fused multiply-add in the recurrence.

**Comment by mreineck** [comment]
I fear that won't help, because I saw in my own code that the compiler already generates all possible fused instructions autmatically. The new structure of the recurrence is unfortunately not as suited for fused operations as the original one.

**Pull request merged**
